CREATE TABLE `t_user_info` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '会员号',
  `open_id` varchar(100) NOT NULL DEFAULT '' COMMENT '微信openId',
  `union_id` varchar(100) NOT NULL DEFAULT '' COMMENT '微信unionId',
  `parent_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '锁粉对象ID,如未锁粉,则为0',
  `name` varchar(100) NOT NULL DEFAULT '' COMMENT '姓名',
  `nick_name` varchar(50) NOT NULL DEFAULT '' COMMENT '昵称',
  `id_number` varchar(100) NOT NULL DEFAULT '' COMMENT '身份证号',
  `phone_number` varchar(100) NOT NULL DEFAULT '' COMMENT '手机号',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '加入方式, 0-自主注册,1-货手邀请 2-购买商品',
  `team_id` int(20) unsigned NOT NULL DEFAULT '0' COMMENT '团队ID',
  `team_name` varchar(50) NOT NULL DEFAULT '' COMMENT '团队昵称',
  `level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '用户等级, 0-普通会员,1-黄金会员,2-铂金会员,3-钻石会员',
  `head_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否团队长福利生效，1-是，0-否',
  `head_exist_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否存在在团队长列表，1-是，0-否',
  `bind_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否绑定手机号,0-未绑定,1-已绑定',
  `icon` varchar(1000) NOT NULL DEFAULT '' COMMENT '头像图片地址',
  `qr_icon` varchar(200) NOT NULL DEFAULT '' COMMENT '微信二维码图片地址',
  `withdraw_first_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '每单位时间内首次发送时间',
  `withdraw_times` int(11) NOT NULL DEFAULT '0' COMMENT '单位时间提现次数',
  `del_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除标记',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `bind_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '手机号绑定时间',
  `admire_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近一次锁粉时间',
  `join_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间(升级为初级会员时间)',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `effect_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '团队长福利生效时间',
  `un_effect_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '团队长福利失效时间',
  `zero_startup` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否0元开店: 0-否，1-是',
  `invite_code` varchar(20) NOT NULL DEFAULT '' COMMENT '邀请码',
  `consultant_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '升级成顾问时间',
  `senior_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '升级成高级顾问时间',
  `in_kawei` int(4) unsigned NOT NULL DEFAULT '0' COMMENT '是否参与卡位活动',
  `task_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '0未完成,已完成',
  `last_qrcode_time` datetime NOT NULL DEFAULT '1971-01-01 00:00:00' COMMENT '弹窗提醒二维码时间',
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_join_time` (`join_time`),
  KEY `idx_level` (`level`),
  KEY `idx_bind_time` (`bind_time`),
  KEY `idx_admire_time` (`admire_time`),
  KEY `idx_union_id` (`union_id`),
  KEY `idx_member_head` (`member_id`,`head_flag`),
  KEY `idx_open_id` (`open_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_invite_code` (`invite_code`),
  KEY `idx_member_id` (`member_id`)
) ENGINE=InnoDB AUTO_INCREMENT=165809 DEFAULT CHARSET=utf8mb4 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC COMMENT='会员表'