CREATE TABLE `t_user_relation` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '会员号',
  `user_rank` tinyint(2) NOT NULL DEFAULT '0' COMMENT '当前用户等级',
  `parent_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '父ID',
  `first_consultant` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '第一个顾问',
  `first_consultant_parent` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '第一个顾问的父id',
  `cultivation_consultant` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '育成顾问',
  `senior_consultant` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '高级顾问',
  `senior_consultant_parent` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '高级顾问的父id',
  `senior_cultivation_consultant` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '高级育成顾问',
  `del_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标识：0-默认，1-已删除',
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_member_id` (`member_id`) USING BTREE,
  KEY `idx_1st_consultant` (`first_consultant`),
  KEY `idx_2nd_consultant` (`cultivation_consultant`),
  KEY `idx_member_del` (`member_id`,`del_flag`)
) ENGINE=InnoDB AUTO_INCREMENT=31984 DEFAULT CHARSET=utf8 COMMENT='用户关系表'