CREATE TABLE `t_user_profit` (
  `profit_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '用户id',
  `from_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '收益来源id',
  `order_id` varchar(30) NOT NULL DEFAULT '' COMMENT '收益来源订单',
  `order_member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '收益来源订单下单用户',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '0,待到账1,已到账,2已失效',
  `order_amount` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '订单金额',
  `profit_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '佣金',
  `settle_flag` tinyint(3) DEFAULT '0' COMMENT '是否结算0 未结算，1 已结算',
  `settle_time` timestamp NULL DEFAULT '2000-01-01 00:00:00' COMMENT '结算时间',
  `type` tinyint(3) NOT NULL DEFAULT '0' COMMENT '收益类型',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '删除标记',
  `user_rank` tinyint(1) DEFAULT NULL COMMENT '会员等级',
  `base_amount` decimal(11,2) DEFAULT NULL COMMENT '计算基数',
  `rate_factor` decimal(6,5) DEFAULT NULL COMMENT '比例因子',
  `rule_id` tinyint(1) DEFAULT NULL COMMENT '达成的规则id',
  `biz_type` tinyint(3) NOT NULL DEFAULT '0' COMMENT '业务类型中的该属性与收益表中bizType保持一致）',
  PRIMARY KEY (`profit_id`),
  KEY `index_member_id` (`member_id`),
  KEY `index_order_id` (`order_id`),
  KEY `index_order_member_id` (`order_member_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_settle_flag` (`settle_flag`,`settle_time`)
) ENGINE=InnoDB AUTO_INCREMENT=509893 DEFAULT CHARSET=utf8 COMMENT='用户收益表'