CREATE TABLE `wfm_member_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '??id',
  `user_name` varchar(100) NOT NULL COMMENT '???',
  `nick_name` varchar(50) NOT NULL COMMENT '??',
  `avatar_url` varchar(300) NOT NULL DEFAULT '' COMMENT '??????',
  `status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '???0?????1?????2?……com.tiefan.wfm.intf.enums.LoginStatusEnum?',
  `reg_info_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '???????0????(??)?1????……com.tiefan.wfm.intf.enums.RegInfoStatusEnum?',
  `gender` varchar(4) NOT NULL DEFAULT '' COMMENT '?? ? ?',
  `login_time` datetime DEFAULT NULL COMMENT '????',
  `finger_print` varchar(300) NOT NULL DEFAULT '' COMMENT '??????',
  `mobile_tel` varchar(32) NOT NULL DEFAULT '' COMMENT '??',
  `password` varchar(300) NOT NULL DEFAULT '' COMMENT '??',
  `email` varchar(100) NOT NULL DEFAULT '' COMMENT '??',
  `card_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '????',
  `id_number` varchar(100) NOT NULL DEFAULT '' COMMENT '???',
  `id_card_flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '?????0?????1?????',
  `id_card_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '????',
  `integral` int(20) NOT NULL DEFAULT '0' COMMENT '??',
  `level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '????',
  `birthday` varchar(32) NOT NULL DEFAULT '' COMMENT '??',
  `constellatory` tinyint(4) NOT NULL DEFAULT '0' COMMENT '??',
  `occupation` varchar(100) NOT NULL DEFAULT '' COMMENT '??',
  `nation` varchar(100) NOT NULL DEFAULT '' COMMENT '????',
  `interest` varchar(100) NOT NULL DEFAULT '' COMMENT '????',
  `income` tinyint(4) NOT NULL DEFAULT '0' COMMENT '??',
  `identify_flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '?????com.tiefan.wfm.intf.enums.AuthenticationGradeEnum?0?????1??????2??????',
  `identify_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '????',
  `key_version` int(11) NOT NULL DEFAULT '1' COMMENT '????',
  `real_name` varchar(128) NOT NULL DEFAULT '' COMMENT '????????????????',
  `isp_name` varchar(128) NOT NULL DEFAULT '' COMMENT '??????',
  `weixin` varchar(64) NOT NULL DEFAULT '' COMMENT '???',
  `company` varchar(64) NOT NULL DEFAULT '' COMMENT '????',
  `edu_code` int(11) NOT NULL DEFAULT '0' COMMENT '??code',
  `edu_name` varchar(10) NOT NULL DEFAULT '' COMMENT '??name',
  `province_code` int(11) NOT NULL DEFAULT '0' COMMENT '????code',
  `province_name` varchar(64) NOT NULL DEFAULT '' COMMENT '????name',
  `city_code` int(11) NOT NULL DEFAULT '0' COMMENT '????code',
  `city_name` varchar(64) NOT NULL DEFAULT '' COMMENT '????name',
  `district_code` int(11) NOT NULL DEFAULT '0' COMMENT '????code',
  `district_name` varchar(64) NOT NULL DEFAULT '' COMMENT '????name',
  `add_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '????(????)',
  `update_uid` int(11) NOT NULL DEFAULT '0' COMMENT '???uid',
  `update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '????',
  `del_flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '?????0?????1?????',
  `batch_code` varchar(128) NOT NULL DEFAULT '' COMMENT '??????',
  `step_count` varchar(128) NOT NULL DEFAULT '' COMMENT '?????',
  `zhima_score` varchar(128) NOT NULL DEFAULT '' COMMENT '?????',
  `quality2000` tinyint(3) NOT NULL DEFAULT '0' COMMENT '????2000??, 0-?, 1-?',
  `register_channel` varchar(128) NOT NULL DEFAULT '' COMMENT '???? ?????????????',
  `register_source_app` int(11) NOT NULL DEFAULT '0' COMMENT '???????, ?? ?????? ?? ????????????????????????',
  `app_id` varchar(20) NOT NULL DEFAULT 'xhy' COMMENT 'appId',
  PRIMARY KEY (`id`),
  UNIQUE KEY `wfm_member_info_member_id_uindex` (`member_id`),
  KEY `idx_id_number` (`id_number`,`card_type`),
  KEY `IDX_MOBILE_TEL` (`mobile_tel`),
  KEY `IDX_NICK_NAME` (`nick_name`),
  KEY `user_index` (`user_name`,`app_id`),
  KEY `dx_add_time` (`add_time`)
) ENGINE=InnoDB AUTO_INCREMENT=41732285 DEFAULT CHARSET=utf8 COMMENT='?????'