CREATE TABLE `wfm_login_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '会员id',
  `user_name` varchar(100) NOT NULL DEFAULT '' COMMENT '用户名',
  `ip_addr` varchar(32) NOT NULL DEFAULT '' COMMENT 'ip地址',
  `p_value` varchar(32) NOT NULL DEFAULT '' COMMENT 'p值',
  `finger_print` varchar(300) NOT NULL DEFAULT '' COMMENT '指纹（风控）',
  `operate_type` tinyint(2) NOT NULL DEFAULT '0' COMMENT '1-注册 2-登录',
  `device_no` varchar(100) NOT NULL DEFAULT '' COMMENT '设备号',
  `system_no` varchar(20) NOT NULL DEFAULT '' COMMENT 'android / ios',
  `device_type` varchar(10) NOT NULL DEFAULT '' COMMENT 'APP/H5',
  `version` varchar(32) NOT NULL DEFAULT '' COMMENT '版本',
  `add_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '删除标记（0：未删除，1：已删除）',
  `device_token` varchar(100) NOT NULL DEFAULT '' COMMENT '友盟设备号',
  `device_name` varchar(100) NOT NULL DEFAULT '' COMMENT '设备名称',
  `term_sys_version` varchar(128) NOT NULL DEFAULT '' COMMENT '系统版本号',
  `term_model` varchar(128) NOT NULL DEFAULT '' COMMENT '设备型号',
  `term_id` varchar(128) NOT NULL DEFAULT '' COMMENT '设备唯一标识',
  `network` varchar(128) NOT NULL DEFAULT '' COMMENT '网络',
  `network_operator` varchar(128) NOT NULL DEFAULT '' COMMENT '网络运营商',
  `major_app_version` varchar(128) NOT NULL DEFAULT '' COMMENT '主APP版本号',
  `app_version` varchar(128) NOT NULL DEFAULT '' COMMENT 'app版本号',
  `app_type` int(11) NOT NULL DEFAULT '0' COMMENT 'app类型（0、未知，1、FDS急用钱，2、TNP小黑鱼，3、JTA融360，4、LAS彩票，5、LICAI珊瑚理财，6、H5-M站，7、……com.tiefan.wfm.intf.enums.MemberIdBizzEnum）',
  `register_channel` varchar(128) NOT NULL DEFAULT '' COMMENT '注册渠道',
  `position_lon` varchar(32) NOT NULL DEFAULT '' COMMENT '经度',
  `position_lat` varchar(32) NOT NULL DEFAULT '' COMMENT '纬度',
  `app_id` varchar(20) NOT NULL DEFAULT 'xhy' COMMENT 'appId',
  PRIMARY KEY (`id`),
  KEY `idx_member_id` (`member_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58011448 DEFAULT CHARSET=utf8 COMMENT='登录记录日志'