CREATE TABLE `wfm_member_rights` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '会员id',
  `member_phone` varchar(64) NOT NULL DEFAULT '' COMMENT '会员手机号',
  `member_level` tinyint(3) NOT NULL DEFAULT '0' COMMENT '会员等级：0:普通会员，1：黄金会员',
  `super_member_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '高级会员状态：0：未付费，1：已付费，2：已到期，3：已冻结',
  `active_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '生效时间',
  `expire_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '有效时间',
  `frozen_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '冻结时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_uid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新人id',
  `update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '删除标记（0：未删除，1：已删除）',
  `app_id` varchar(20) NOT NULL DEFAULT 'xhy' COMMENT 'appId',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_member_id` (`member_id`) USING BTREE,
  KEY `idx_member_phone` (`member_phone`),
  KEY `idx_member_level` (`member_level`),
  KEY `idx_super_member_status` (`super_member_status`),
  KEY `idx_active_time` (`active_time`),
  KEY `idx_expire_time` (`expire_time`),
  KEY `idx_frozen_time` (`frozen_time`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=31439314 DEFAULT CHARSET=utf8 COMMENT='会员权益表'